### ISSUE TITLE
List all publishers on IATI Registry

### ISSUE THREAD

**Issue by notshi** [aidtransparency/iati-data#1] opened 2019-04-05 14:38 UTC
Also raised here - https://github.com/devinit/D-Portal/issues/516

We are currently missing a full list of publishers on the Registry.

There are 16 publishers identifying as US-GOV-* (2, 6, 7, 9, 10, 11, 13, 14, 15, 16, 17, 19, 20, 21, 22, 26) and the files are published under [US-GOV-1](https://iatiregistry.org/publisher/usaid) and [US-USAGOV](https://iatiregistry.org/publisher/unitedstates).

**Comment by notshi** [comment] 2019-04-05 18:59
Many thanks to the Dashboard, here is a list of them - http://dashboard.iatistandard.org/reporting_orgs.html

All of these publishers currently have pages on d-portal - for example: [US-GOV-11](http://www.d-portal.org/ctrack.html?publisher=US-GOV-11#view=main)

**Comment by andylolz** [comment] 2019-04-05 21:10
@notshi I dunno if it’s of interest / use, but the [org ID finder](https://andylolz.github.io/org-id-finder/) API can help identify some of these, [e.g. US-GOV-10](https://api.morph.io/andylolz/org-id-finder/data.json?key=wFTSIH61nwMjLBhphd4T&query=select%20*%20from%20%22organisations%22%20where%20org_id%20%3D%20%22US-GOV-10%22).

**Comment by notshi** [comment] 2019-04-08 23:23
Thanks, @andylolz! We really need an official, definitive list - it's a question of policy more than anything.

**Comment by andylolz** [comment] 2019-04-09 08:29
> official, definitive list

^^ Org ID finder doesn’t use a centralised list, but instead derives them all from publishers’ own org files. The idea is that self-reported is canonical.

The `self-reported=False` in the [US-GOV-10 example](https://api.morph.io/andylolz/org-id-finder/data.json?key=wFTSIH61nwMjLBhphd4T&query=select%20*%20from%20%22organisations%22%20where%20org_id%20%3D%20%22US-GOV-10%22) is there because this was reported by [US-USAGOV](US-USAGOV), as you have spotted.

**Comment by andylolz** [comment] 2019-04-09 15:05
Yes, that’s true – but we digress.

---

So look – what is the proposed fix for this ticket?

I think there are two ways this could go:

 1. `US-USAGOV` and `US-GOV-1` change all the `reporting-org`s in their data, so that everything has a `reporting-org/@ref` of either `US-USAGOV` or `US-GOV-1`
 2. IATI relaxes the rule about `reporting-org`s matching the org ID in the registry.

The problem with solution 1 is: I think they’d then need to update IATI identifiers, since these are supposed to start with the reporting organisation’s org ID:

> This MUST be prefixed with EITHER the current IATI organisation identifier for the reporting organisation (reporting-org/@ref) OR a previous identifier reported in other-identifier

This is a problem, because IATI identifiers are not supposed to change. Maybe they could specify an `other-identifier` with code B9 (Other Organisation Identifier), and then leave the IATI identifiers as they are.

What do you think @notshi @markbrough?

**Comment by notshi** [comment] 2019-04-09 15:41
Could we ask someone with write-access to add those missing publishers to the registry?

**Comment by andylolz** [comment] 2019-04-09 16:14
> Could we ask someone with write-access to add those missing publishers to the registry?

Not sure I understand. How/where would the registry list them?

These organisations are not actually publishers, which is why they don’t exist on this list: https://iatiregistry.org/publisher

The State Dept publishes on their behalf. So I think it is correct that they’re not listed as a publisher on the registry, because they are not registry publishers.

**Comment by notshi** [comment] 2019-04-09 16:29
The registry has publishers like [this one](https://iatiregistry.org/publisher/123345678-test) in the database even if they are not listed on that publisher list (I'm assuming this is down to having 0 datasets). I don't see why we can't add useful data in there alongside all the chaff.

Otherwise, could there be a list for reporting-orgs?

**Comment by andylolz** [comment] 2019-04-09 20:58
> even if they are not listed on that publisher list 

Good point yes. Edited above accordingly.

---

Let me quote [the bit from the standard](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/reporting-org/) again (emphasis mine):

> All activities in an activity xml file must contain the same `@ref` AND this `@ref` must be the same as the [org ID] recorded in the registry publisher record **of the account under which this file is published.**

The very last bit is important! The idea is to prevent "identity theft". The org ID in the registry metadata is confirmed by the secretariat on signup. Data subsequently published by that publisher must include a `reporting-org/@ref` that matches the org ID in the registry metadata. Otherwise any publisher can publish data with a `reporting-org/@ref` of "GB-CHC-299717" and it’ll appear with [Send A Cow](https://iatiregistry.org/publisher/sendacow)’s data on d-portal.

Of course it’s all traceable, but you can appreciate there is potential for reputational damage here, which is presumably why this rule was added.

So adding stub accounts for organisations won’t really help, because those accounts aren’t actually publishing the relevant data. Also, there would be a question mark over who is responsible for adding and maintaining these stub accounts.

**Comment by notshi** [comment] 2019-04-09 21:41
Think we might make it obvious on d-portal that [these publishers](http://dashboard.iatistandard.org/reporting_orgs.html) are not playing by the rules.

By the way, where is this 'magic knowledge' to find out who publishes on whose behalf?

**Comment by andylolz** [comment] 2019-04-09 21:59
> Think we might make it obvious on d-portal that [these publishers](http://dashboard.iatistandard.org/reporting_orgs.html) are not playing by the rules.

^^ Great! This is probably a good plan.

> By the way, where is this 'magic knowledge' to find out who publishes on whose behalf?

Err how do you mean exactly? Not sure I follow.

**Comment by notshi** [comment] 2019-04-12 14:11
> The State Dept publishes on their behalf. So I think it is correct that they’re not listed as a publisher on the registry, because they are not registry publishers.

Is there somewhere to get such information? I might be missing something! Wondering if there are other publishers on the registry that do the same thing and that this mapping is out there.

**Comment by andylolz** [comment] 2019-04-12 14:42
Ah I see! Err, let me put it differently:

`US-USAGOV` publishes on their behalf. So I think it is correct that they’re not listed as a publisher on the registry, because they are not registry publishers.

**Comment by andylolz** [comment] 2019-07-24 11:39
Closing this, because I think it is probably an issue for https://github.com/iati/ckanext-iati

**Closed by andylolz** 2019-07-24 11:39 UTC
